# Use source repos
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"

# Sync global general packages
brew "bash"
brew "bash-completion"
brew "vim"
brew "git"
brew "the_silver_searcher"
brew "fzf"
brew "tmux"
brew "reattach-to-user-namespace"
brew "exercism"
brew "shfmt"

# Sync global JavaScript packages
brew "nvm"

# Sync apps
cask "1password"
cask "alacritty"
cask "rescuetime"
